### ISSUE TITLE
Renewal of Modified Files and Auto-Deletion of Manually Added Files

### ISSUE THREAD

**Issue by chzheng2000** [skyzh/canvas_grab#126]
I find that any modification on downloaded file will be recovered as the program re-downloads files to cover the modified version. That means we cannot directly take notes on slides, which frustrated me a lot when yesterday I suddenly found out my notes were totally gone. 
Besides, for files I manual added to the course directory (like some relevant materials), they will also be removed automatically by the program. I have set the configuration of "delete_file" to "false" but it seems not to solve the problem.
Currently, I have to copy files somewhere else and then take notes on the copy, which causes great inconvenience.
I am using the latest version of canvas_grab and macOS BigSur 11.2.2.
I would appreciate it if you could try to solve the problem. It used to work fine with the previous version. :)

**Comment by chzheng2000** [comment]
For example, I have modified "2020-教学大纲-计算文本分析.docx". When I run the program, it shows as below and my modified file is gone.
<img width="461" alt="be41533e3e9ce6f0710fcaf2081e435e" src="https://user-images.githubusercontent.com/61909853/109444901-490aad00-7a79-11eb-98e5-6bbf2710dac3.png">

**Comment by skyzh** [comment]
Firstly, apologize for your lost notes. Hope that you have found them back. But for this issue, yes, this is how our tools is intended to work. canvas_grab keeps exactly the same copy and structure as the remote Canvas LMS. The reason behind this is that, files on remote would be updated by teachers, and we always want our users to have the latest copy.

If you want to take notes, it is recommended to copy the files out of canvas_grab download folders and manage them yourselves.

At the same time, I am also considering adding some functionalities like "recover old files". This way, if any file is updated on remote, the old file will be safely stored in a special location.

**Comment by skyzh** [comment]
```
for files I manual added to the course directory (like some relevant materials), they will also be removed automatically by the program
```

This is not expected. I'll look into this.

```
It used to work fine with the previous version
```

canvas_grab v1 uses a complex sync algorithm which confuses me a lot, so I turned to this simple solution in v2 :)

**Comment by chzheng2000** [comment]
Thanks for your reply. I will accommodate the features. Still, thanks for your contribution to such a convenient program:)

**Comment by skyzh** [comment]
You may now update to v2.0.5 or latest master branch, which introduces "recovery" folder and fixed a bug.
