### ISSUE TITLE
Release Archive is too big

### ISSUE THREAD

**Issue by danyang685** [skyzh/canvas_grab#13]
Package in a virtual environment will help to shrink the size of release archive, you may have a try.
It contains only 623 files now, 599 of these are timezone files.
```powershell
cd .\canvas_grab\
git checkout master
pip install virtualenv
.\venv\Scripts\activate.ps1
pip install -r requirements.windows.txt
pip install pyinstaller
pyinstaller main.py --hidden-import pkg_resources.py2_warn --add-data 'config.example.toml;.' --add-data 'LICENSE;.' --add-data 'README.md;.' -n canvas_grab
```

**Comment by skyzh** [comment]
Thanks! I tried packaging on macOS in virtualenv, but it turned out that pyinstaller still packages timezone file. I'll try your script.

**Comment by skyzh** [comment]
It turns out that `canvasapi` requires pytz, which in turn leads to timezone files.

**Comment by skyzh** [comment]
```
canvasapi==0.15.0
  pytz==2019.3
  requests==2.23.0
    certifi==2019.11.28
    chardet==3.0.4
    idna==2.9
    urllib3==1.25.8
  six==1.14.0
colorama==0.4.3
pipdeptree==0.13.2
  pip==20.0.2
retrying==1.3.3
  six==1.14.0
setuptools==45.3.0
toml==0.10.0
tqdm==4.43.0
wheel==0.34.2
```

**Comment by danyang685** [comment]
Using virtualenv will trim a lot of unused stuff like tk/tcl and unused builtin librarys.

**Comment by skyzh** [comment]
I've updated the building file. Let's wait and see.

**Comment by skyzh** [comment]
The package is a little bit smaller now. https://github.com/skyzh/canvas_grab/releases/tag/v1.1.3

**Comment by skyzh** [comment]
We may try:

- [ ] https://github.com/pyinstaller/pyinstaller/wiki/Recipe-remove-tkinter-tcl
- [ ] https://github.com/pyinstaller/pyinstaller/wiki/Recipe-pytz-zip-file

To eliminate these packages
