### ISSUE TITLE
locked file in module mode cause canvas_grab crash

### ISSUE THREAD

**Issue by wyjzxc** [skyzh/canvas_grab#142]
![image](https://user-images.githubusercontent.com/49339996/112317415-fd010000-8ce6-11eb-9990-c8af878f1567.png)
I'm using canvas-grab v2.0.7 and it worked well at first. But a few days ago it can' work because of this error.
Thanks!

**Comment by skyzh** [comment]
You may switch to `As-is in file list` mode by running `configure.ps1` to bypass this issue.

By the way, could you find out what status the file is in from Canvas LMS? You may first go to "Module" page in that course.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4198311/112323803-14db8280-8ced-11eb-970e-1fe3b62f8004.png">

Then, click into the file you suspect that caused this error. You may find URL like `https://oc.sjtu.edu.cn/courses/xxxx/files/2246621?module_item_id=xxxx`.

And then, I could have a better idea what is exactly happening and fix this bug.

**Comment by wyjzxc** [comment]
Thanks! I tried to switch to `As-is in tile list` mode and it worked well.
![image](https://user-images.githubusercontent.com/49339996/112596269-8ed34f00-8e46-11eb-9e85-73bb410376a0.png)
This is the module where the problem happens. In this module ,4 files in the middle are locked and the fisrt one's link and the last one's are `https://oc.sjtu.edu.cn/courses/29686/pages/xue-xi-mu-biao?module_item_id=382602` and `https://oc.sjtu.edu.cn/courses/29686/files/2412604?module_item_id=424873`. The locked files' link looks similar to the last file's.

**Comment by skyzh** [comment]
Okay, so the issue is caused by locked files. I'll fix this soon.

**Comment by skyzh** [comment]
You may download latest version from https://github.com/skyzh/canvas_grab/archive/refs/heads/master.zip or https://git.sjtu.edu.cn/iskyzh/canvas_grab . If the issue still exists, feel free to reopen this issue.
