### ISSUE TITLE
下载图片的时候有点问题

### ISSUE THREAD

**Issue by sjtu-flz** [skyzh/canvas_grab#16]
好像不能下载在公告里面的图片， 然后只要有一个下载不成 ，后面的文件
就都下载不成了（要是能跳过或许更好）
![3](https://user-images.githubusercontent.com/53403083/76312027-27b32d00-630d-11ea-96df-f8c5a09440ea.PNG)
![4](https://user-images.githubusercontent.com/53403083/76312033-28e45a00-630d-11ea-829e-38f50273b325.PNG)

**Comment by skyzh** [comment]
Thanks for your report! I’ll look into that.

**Comment by skyzh** [comment]
This error should have been fixed in v1.0. Would you please try downloading latest release?

**Comment by skyzh** [comment]
Click [here](https://github.com/skyzh/canvas_grab/archive/master.zip) if you have Python installed. Click [here](https://github.com/skyzh/canvas_grab/releases) if you want prebuilt binary. By the way, the latest version may have a different config file from the version you're using. Have a try!

**Comment by sjtu-flz** [comment]
The latest version works very well !
Thanks for patiently answering me!

**Comment by skyzh** [comment]
Glad to know that. I'll close this issue for now.
