### ISSUE TITLE
Course name with directory separators

### ISSUE THREAD

**Issue by squnit** [skyzh/canvas_grab#160]
If a course has directory separators such as `/`, then they will produce nested directories, which is not the desired behavior. For example, if a course has the name `CS/Math 101`, then it will produce the following directory structure
```
- CS
  - Math 101
    -  ...
```
I believe we should replace these special characters (for example, replace all directory separators with `-`).

**Comment by skyzh** [comment]
Looks good! Would you please send a PR for this?
