### ISSUE TITLE
Force users to review LICENSE before running this program

### ISSUE THREAD

**Issue by skyzh** [skyzh/canvas_grab#29]
Related FAQ: https://sv.sjtu.edu.cn/ask/?q-248.html

The administrator said that:

> 课程分本科生课程、研究生课程、自建课程没有完全统一的命名规则。 友情提示一下三位参与项目的同学。我们并不反对利用程序提供的API进行相关辅助插件的开发应用。但如果造成教师版权资源的泄露，（教学视频、图书馆教程材料）你们需要承担相关责任。

But when it comes to copyright issues, it is not the maintainers of this project that should be blamed.

**Users should be responsible for their own actions.** The LICENSE clearly stated that:

```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
```

Therefore, to make sure that every user know we **do not provide any warranty of any kind** in this software, we should let users check LICENSE before running this program.

**It's ridiculous, and impossible, for arbitrary users maintaining this project, to be responsible for others who upload SJTU course materials online.** I should state that *contributors* are not *maintainers*, and *maintainers* are not necessarily SJTU students. A total of 3 GitHub users *contributed* to this project in the past. And currently, this project has two active *maintainers*.

Also, it should be made clear that this project is not solely intended for SJTU open canvas. Personally, I made this piece of script for automating the downloading file process for *ANY* Canvas LMS website. Only two functionalities are SJTU-specific, and require users to manually enable them:

1. auto renaming folder with SJTU course naming scheme
2. resolving (but not downloading) SJTU course video URL

**canvas_grab never share your information, and never bypass limitations of Canvas.** This program DOES NOT intentionally share what you've downloaded online. They are just saved in your local folders. Furthermore, canvas_grab can only access resource that users have access to. This program cannot bypass limitations of Canvas LMS. Therefore, even if there's any leak of copyright material, it is not the maintainers, but the users who use this software, that should take responsibility for his or her action.

For example, you use Chrome to download some copyright material from MIT intra-net, and upload it to YouTube, which violates the copyright policy. You can not blame Chrome developers for your action, as Chrome is just the tool a user use to access resource, and only by providing valid credentials can Chrome download resource for a user. The same applies to canvas_grab. We just automate the process of downloading with web browser.

We are acknowledged of the concerns expressed by SJTU open canvas administrators. Therefore, we enforced that user should review LICENSE before running this program in https://github.com/skyzh/canvas_grab/pull/30 .

Again, thank everyone who take initiative to test and use this software. Hope this software can free you from manually downloading every single file one by one.

**Comment by ElectronicElephant** [comment]
Take it easy...
