### ISSUE TITLE
Courses with NO `FILES` but `MODULES`

### ISSUE THREAD

**Issue by ElectronicElephant** [skyzh/canvas_grab#33]
It seems that some teachers don't give the permission to students to view files but publish everything in `modules`. See below.

![image](https://user-images.githubusercontent.com/20351686/76704986-9cc0a100-6717-11ea-953f-7f785f472851.png)

Any ideas?

**Comment by skyzh** [comment]
These files should be in "unfiled" folder in files. Would you please check your `files/` folder?

**Comment by skyzh** [comment]
I just find that there's no "files" section in your screenshot. That's weird.

**Comment by skyzh** [comment]
Thanks for your report! I'll fix this in next few days, together with #19
