### ISSUE TITLE
Download Course Video

### ISSUE THREAD

**Issue by danyang685** [skyzh/canvas_grab#4]
Is it possible to:

- ~~download files by section~~
- download embedded videos linked to vshare.sjtu.edu.cn
- ~~download the books linked to jcbks.lib.sjtu.edu.cn~~

**Comment by skyzh** [comment]
The first one and the second one might be easy to implement, but the last one could be hard, as downloading from library requires a proxy. By the way, I think ebooks in our library are not intended for downloading.

**Comment by skyzh** [comment]
I might try implementing video downloading in the following days

**Comment by skyzh** [comment]
Just had a look at the video sharing website in our school. Our school uses HTTP Live Streaming (HLS) for distributing video content, which is relatively hard to download. We may export all pages containing HLS video, and use other tools to download the video.

**Comment by skyzh** [comment]
Video from v.sjtu.edu.cn can be downloaded directly with ffmpeg. This program may generate scripts for downloading these videos.
However, these from vshare.sjtu.edu.cn might require extra work.

**Comment by QuteSaltyFish** [comment]
I think downloading the video is great! Hope to see this function online

**Comment by danyang685** [comment]
Downloading video from vshare.sjtu.edu.cn need provide with a logged in cookie for authentication. It's very easy for someone who has basic knowledge about HTTP, but it's necessary to make it much easier for common users.

The key to implement this feature is to recognize the CAPTCHA on the jaccount sso page in a very simple way.

**Comment by skyzh** [comment]
I just made a new commit supporting generating downloading script from "v.sjtu.edu.cn" web pages. Have a try!

I'll update documentation and config file docs tomorrow. This release may be published next week.

**Comment by skyzh** [comment]
```toml
[SYNC]
# Enable video download from v.sjtu.edu.cn
ENABLE_VIDEO = true
```

**Comment by danyang685** [comment]
vshare is not supported yet.

**Comment by Neight99** [comment]
> Downloading video from vshare.sjtu.edu.cn need provide with a logged in cookie for authentication. It's very easy for someone who has basic knowledge about HTTP, but it's necessary to make it much easier for common users.
> 
> The key to implement this feature is to recognize the CAPTCHA on the jaccount sso page in a very simple way.

我觉得可以像MXWXZ/sjtu-automata 那样直接用tesseract-ocr识别？Windows下也可以直接下载图片弹窗显示之后让用户手动输入。

**Comment by skyzh** [comment]
@Neight99 自动登陆 jAccount 的话 https://github.com/PhotonQuantum/pysjtu 可以直接用。我不打算自己写了（

**Comment by skyzh** [comment]
My main concern is that coding for vshare.sjtu.edu.cn might introduce tremendous effort. It's relatively easy to support v.sjtu.edu.cn . We just supply the URL to ffmpeg and let ffmpeg handle the rest. But for vshare.sjtu.edu.cn, we need to

1. auto login
2. download video with cookie

This could imply a larger codebase.

**Comment by skyzh** [comment]
Here we maintainers decided that we do not take risk of adding support for downloading copyright materials. Especially, vshare.sjtu.edu.cn, where downloading video requires explicit log in. So, we're going to close this issue.

Also I've written some [explanations](https://github.com/skyzh/canvas_grab/issues/29) for how we handle these issues related with copyright material.
