### ISSUE TITLE
Interrupt during checkpointing will break checkpoint file

### ISSUE THREAD

**Issue by danyang685** [skyzh/canvas_grab#40]
Interrupt during checkpointing will leave a broken file

**Comment by skyzh** [comment]
One way to fix this:
- create `.checkpoint.tmp`
- remove `.checkpoint`
- move `.checkpoint.tmp` to `.checkpoint`

**Comment by skyzh** [comment]
Interrupt during downloading will indeed leave a broken file. However, as this file is not checkpointed, we will re-download it after restarting the program. We may add this piece of information into README.

**Comment by danyang685** [comment]
However, there will be an option called NEVER_OVERWRITE_FILE soon.

**Comment by danyang685** [comment]
[#42 ] fixed.
