### ISSUE TITLE
main.py throws exception: "ValueError: time data '2020-03-19T06:33:33Z' does not match format '%Y-%m-%dT%H:%M:%S%z'"

### ISSUE THREAD

**Issue by shrubbroom** [skyzh/canvas_grab#55]
I use the latest release and run from the source code in WSL. The main.py throws 

```
Traceback (most recent call last):
  File "./main.py", line 381, in <module>
    main()
  File "./main.py", line 86, in main
    process_course(course)
  File "./main.py", line 341, in process_course
    file.updated_at, '%Y-%m-%dT%H:%M:%S%z').timestamp()
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
```

`ValueError: time data '2020-03-19T06:33:33Z' does not match format '%Y-%m-%dT%H:%M:%S%z'`
after each file is downloaded. I change the time format from `'%Y-%m-%dT%H:%M:%S%z'` to `'%Y-%m-%dT%H:%M:%Sz'`, and everything goes well. I don't know much about the time format in Python so I am not sure whether it will happen on other platforms or not.

**Comment by skyzh** [comment]
Thanks for your report! As we haven't tested canvas_grab in Linux environment, we really missed this point. I'll fix this soon.

**Comment by skyzh** [comment]
This is a Python-related issue. Python 3.6 cannot parse "Z" suffix in datetime string. If you upgrade your Python to 3.7+, you may fix this issue without changing code.

Related issue of Python: https://bugs.python.org/issue31800
Some explanation on Stackoverflow: https://stackoverflow.com/questions/53291250/python-3-6-datetime-strptime-returns-error-while-python-3-7-works-well

Would you please try upgrading your Python?

**Comment by skyzh** [comment]
By the way, this piece of code is used to change creation and modification time of a file in filesystem upon first download or update. As you mentioned, you have downloaded all files, then rerun the script. In this way, this section won't be executed. So a better way to test if this works in Python 3.7+ is that, delete one arbitrary downloaded file in files folder, and run the script. If there's no error, then everything goes well.

**Comment by shrubbroom** [comment]
Yes, this solves the problem. Thank you.
