### ISSUE TITLE
May Interrupted By Exception Raised By A Single File

### ISSUE THREAD

**Issue by chzheng2000** [skyzh/canvas_grab#69]
The program can be interrupted immediately if there is something wrong with some specific file and then fails to download the rest. 
For example, there is something wrong with the file "SVM_demo.py". By raising exception of "File download not complete", the program will simply reaches to an end, not continuing to download rest of the undamaged files. This may cause inconvenience. If the specific file remains damaged, I may then no longer download other files either.
<img width="849" alt="截屏2020-04-25 下午12 04 08" src="https://user-images.githubusercontent.com/61909853/80270688-e7f1aa80-86ec-11ea-8121-2509b53402c5.png">
I guess adding some exception handling here in "main.py" could solve the problem and be more user friendly:)
<img width="946" alt="截屏2020-04-25 下午12 05 16" src="https://user-images.githubusercontent.com/61909853/80270746-59c9f400-86ed-11ea-91cd-92c1d686d102.png">

**Comment by skyzh** [comment]
Good idea! I'll implement this later.

**Comment by skyzh** [comment]
I've just fixed this in master branch. Would you please try it out?

Also a side note. If "file download not complete" is raised for all files, that might be an issue with network connection, and we may only wait for Canvas administrators to fix it.

**Comment by chzheng2000** [comment]
Oh thanks, it works fine now ~

**Comment by skyzh** [comment]
Glad to know that! I'll close this issue.
