### ISSUE TITLE
Subheader in module is not supported

### ISSUE THREAD

**Issue by danyang685** [skyzh/canvas_grab#75]
https://github.com/skyzh/canvas_grab/blob/5a3df4d5fd3db71748f5ae69476d9b9b76c8fb08/main.py#L354-L355

In some of my course, there are many subheaders in a module for better items' arrangement. I think it need to be supported.

**Comment by skyzh** [comment]
Sure! They can be put into subfolder under module. Would you please give a screenshot of courses with subheader?

**Comment by danyang685** [comment]
Thank you! There are two examples:

#### Example 1:
![image](https://user-images.githubusercontent.com/29062127/80381296-56905d00-88d3-11ea-8679-b00d65a47793.png)

attibutes: 'title': '补充视频', 'indent': 1, 'type': 'SubHeader'

#### Example 2:


![image](https://user-images.githubusercontent.com/29062127/80381414-7c1d6680-88d3-11ea-91e7-4c1119f04b69.png)

attibutes: 'title': '录播视频', 'indent': 0, 'type': 'SubHeader'

**Comment by danyang685** [comment]
It will be a totally useless feature. Let me close it.
