### ISSUE TITLE
Is whitelist mode of course management possible?

### ISSUE THREAD

**Issue by WanHanxi** [skyzh/canvas_grab#86]
Can we manage courses by selecting courses instead of ignoring? Every semester we have only a few important courses and lots of unimportant courses whose files aren't necessary (e.g. P.E., 军理...). And by selecting course we can easily exclude courses from the previous semesters. I think it will bring us great convenience.

**Comment by skyzh** [comment]
Sure! I will work on this later!

**Comment by skyzh** [comment]
By the way, courses from previous semester should be inaccessible under `oc.sjtu.edu.cn`. How do you observe courses from previous semesters in canvas_grab?

**Comment by WanHanxi** [comment]
Great! Looking forward to this!
I can access them in UMJI canvas `umjicanvas.com`, which is different from SJTU canvas. The first time I use canvas_grab it even downloads all the documents regarding teaching affairs under the course *Undergraduate Students* (missing in SJTU canvas) :joy:

**Comment by skyzh** [comment]
Ohhhh, I really missed this point! Actually most users of this project use oc.sjtu.edu.cn :(

**Comment by skyzh** [comment]
I've just updated master branch to add whitelist mode. You can use `WHITELIST_CANVAS_ID` to filter course ID. The ID can be found in corresponding course URL. For example:
```
https://oc.sjtu.edu.cn/courses/18710
```
Where 18710 is a course ID. Would you please have a try?

If you have any further question, feel free to reopen this issue.

**Comment by WanHanxi** [comment]
It perfectly works! Thxxxxxx!
