### ISSUE TITLE
Prepare for v2.0

### ISSUE THREAD

**Issue by skyzh** [skyzh/canvas_grab#88]
In v2.0, I plan to implement:

- [x] use GraphQL API to batch fetching information
- [x] fine-grained filter
- [x] better terminal-based GUI
- [x] maybe we can use golang instead Python for better binary packaging and coroutine support

**Comment by skyzh** [comment]
It seems that most of our users are running this software from source code. Maybe Python is still a better choice.

**Comment by LuminousXLB** [comment]
Better binary packaging makes it possible to share the program with friends who are not programmers.

But I don't know how to program with golang

**Comment by taraxacum45e9a** [comment]
Better binary packaging makes it possible to share the program with friends who are not programmers.

But I don't know how to program with golang

**Comment by skyzh** [comment]
> Better binary packaging makes it possible to share the program with friends who are not programmers.
> 
> But I don't know how to program with golang

Yep. It seems that most of our users love running from source code. So I'm not sure about this switch.

**Comment by skyzh** [comment]
Impossible to use GraphQL API. It even doesn't support File objects for now, which is canvas_grab key functionality.

**Comment by danyang685** [comment]
Can it start a local http server(like a daemon?) so that it can be accessed with a nice GUI via our web browser? It will also be able to track all files with [watchdog](https://pypi.org/project/watchdog/) for better files management. And automaticly sync the files periodically.

**Comment by skyzh** [comment]
A web frontend may be a good idea 👍

**Comment by skyzh** [comment]
Watchdog has to be running all the time. This may not be taken into consideration.

**Comment by danyang685** [comment]
Watchdog may not a good solution, can we read all the orphan files to compare the MD5 values at startup? It will obviously be faster than redownload the lost files.

**Comment by skyzh** [comment]
> Watchdog may not a good solution, can we read all the orphan files to compare the MD5 values at startup? It will obviously be faster than redownload the lost files.

<del>But how to identify which remote file a local file corresponds to?</del>
Well, we can calculate SHA-256 after download.

**Comment by danyang685** [comment]
Btw, SHA-256 seems to be much safer but slower. Will it be the better choice than MD5?

**Comment by skyzh** [comment]
Hmm... maybe in this case, MD5 / SHA-1 is enough

**Comment by taraxacum45e9a** [comment]
I prefer SHA1

``` console
$ openssl speed sha1 md5 sha256                                                                              [10:47:59]
Doing md5 for 3s on 16 size blocks: 29160748 md5's in 3.00s
Doing md5 for 3s on 64 size blocks: 17167056 md5's in 3.00s
Doing md5 for 3s on 256 size blocks: 7358633 md5's in 3.00s
Doing md5 for 3s on 1024 size blocks: 2200068 md5's in 3.00s
Doing md5 for 3s on 8192 size blocks: 298112 md5's in 3.00s
Doing md5 for 3s on 16384 size blocks: 143494 md5's in 3.00s
Doing sha1 for 3s on 16 size blocks: 24834996 sha1's in 3.00s
Doing sha1 for 3s on 64 size blocks: 16581144 sha1's in 3.00s
Doing sha1 for 3s on 256 size blocks: 8451201 sha1's in 3.00s
Doing sha1 for 3s on 1024 size blocks: 2742269 sha1's in 3.00s
Doing sha1 for 3s on 8192 size blocks: 390682 sha1's in 3.00s
Doing sha1 for 3s on 16384 size blocks: 189333 sha1's in 3.00s
Doing sha256 for 3s on 16 size blocks: 15951686 sha256's in 3.00s
Doing sha256 for 3s on 64 size blocks: 9005843 sha256's in 3.00s
Doing sha256 for 3s on 256 size blocks: 4231027 sha256's in 3.00s
Doing sha256 for 3s on 1024 size blocks: 1332698 sha256's in 3.00s
Doing sha256 for 3s on 8192 size blocks: 185936 sha256's in 3.00s
Doing sha256 for 3s on 16384 size blocks: 94732 sha256's in 3.00s
OpenSSL 1.1.1f  31 Mar 2020
built on: Mon Apr 20 11:53:50 2020 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-P_ODHM/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
md5             155523.99k   366230.53k   627936.68k   750956.54k   814044.50k   783668.57k
sha1            132453.31k   353731.07k   721169.15k   936027.82k  1066822.31k  1034010.62k
sha256           85075.66k   192124.65k   361047.64k   454894.25k   507729.24k   517363.03k
```
