### ISSUE TITLE
Incompatible checkpoint file with 1.4.7

### ISSUE THREAD

**Issue by Vanadylxu** [skyzh/canvas_grab#96]
之前是1.4.7的版本，使用时偶有checkpoint的报错，担心有些课的课件没有完整地下好，于是换成1.7.8，设好参数之后直接就用不了了

以下是异常栈
Traceback (most recent call last):
  File ".\main.py", line 422, in <module>
    main()
  File ".\main.py", line 72, in main
    checkpoint.load()
  File "C:\Users\a\Desktop\canvas_grab-master\checkpoint.py", line 54, in load
    self._checkpoint[k] = CheckpointItem(**v)
TypeError: __init__() missing 1 required positional argument: 'id'
（已经登录成功，并显示我的姓名和id）

**Comment by skyzh** [comment]
感谢。我们正在调查这个问题。

**Comment by skyzh** [comment]
可能是在升级的过程中，`.checkpoint` 文件和之前不兼容了。麻烦删除 `.checkpoint` 文件试一下。（当然所有的文件都会重新下载一遍。）您可以提供一下 `.checkpoint` 文件中的一个 {} 包围的 block，里面应该没有 `id`，这大概是这个错误发生的原因。

**Comment by Vanadylxu** [comment]
感谢，问题已经解决。大概是我更新的时候直接替换了源文件夹导致的。

----- 原始邮件 -----
发件人: "Alex Chi" <notifications@github.com>
收件人: "skyzh/canvas_grab" <canvas_grab@noreply.github.com>
抄送: "Vanadylxu" <vanadylxu@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期日, 2020年 6 月 14日 上午 11:08:07
主题: Re: [skyzh/canvas_grab]  __init__() missing 1 required positional argument: 'id' (#96)

可能是在升级的过程中，`.checkpoint` 文件和之前不兼容了。麻烦删除 `.checkpoint` 文件试一下（当然所有的文件都会重新下载一遍。）

**Comment by skyzh** [comment]
好的。那我就关掉这个 issue 了。
